name: Run all tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install wget zip unzip
      
      - name: Download Godot 3.2.3 Mono
        run: |
          wget -q https://downloads.tuxfamily.org/godotengine/3.2.3/mono/Godot_v3.2.3-stable_mono_linux_headless_64.zip
          unzip Godot_v3.2.3-stable_mono_linux_headless_64.zip
          mv Godot_v3.2.3-stable_mono_linux_headless_64/* .
          mv Godot_v3.2.3-stable_mono_linux_headless.64 godot
          chmod +x godot
      
      - name: Run CliTestRunner (all tests)
        run: |
          ./godot -e -q --build-solutions
          ./godot -s addons/NUG/CliTestRunner.cs
